### PR TITLE
Removed derive() in igcm_out.py, correction on gplot.ncl...

### PR DESCRIPTION
**Pull request by jservonnat**
...and on LinearRegression_UVCDAT.py

### CODE REVIEW

**Comment by jservonnat** [comment]
I had an error on Ciclad because of the igcm_out.py project. It is strange because it was an old version of igcm_out.py that came with climaf 1.2.2. We should double check that we merged all the needed branches.

**Comment by jservonnat** [comment]
Or is it because I've cloned 1.2.2 by default from master and that the changes from 'jerome_dev' are in another version 1.2.3? If so, how can I get this version?

**Comment by senesis** [comment]
Check at https://github.com/senesis/climaf/commits/master if the commit you look for is merged

**Comment by senesis** [comment]
I just pushed tag 1.2.3 , but you can also pull the HEAD of master

**Comment by jservonnat** [comment]
Ok here is what I understand: you merged master into jerome_dev, not jerome_dev in master. That means that it is totally normal that I don't have my changes from jerome_dev in master, but jerome_dev is actually a jerome_dev merged with your master.
It means that if I want to add more modifications I should restart from this merged jerome_dev. Am I correct? If so we need to modify the climaf/__init__.py because it says that this is version 1.2.2 (and not 1.2.3).

**Comment by senesis** [comment]
No. YOU merged (my) branch master in (your) branch jerome_dev, then (in V1.2.3) I merged (your) branch jerome_dev in master. If you pull 1.2.3, that should be OK

**Pull request merged**
